server:
  port: 8001
  servlet:
    context-path: /goods
spring:
  application:
    name: goods
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/goods?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    url: jdbc:mysql://127.0.0.1:3306/order?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123...
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
#      server-addr: 127.0.0.1:8848
      server-addr: host.docker.internal:8848
      config:
        namespace: public
mybatis:
  mapper-locations: classpath:mappers/*.xml
seata:
  # 与 file.conf service 中名字对应
  tx-service-group: goods-tx-group
  application-id: goods-seata-id
  enabled: true
  client:
    tm:
      # 一阶段全局提交结果上报TC重试次数，默认1次，建议大于1。
      commitRetryCount: 3
      # 一阶段全局回滚结果上报TC重试次数，默认1次，建议大于1
      rollbackRetryCount: 3
    undo:
      logTable: undo_log  # 自定义undo表名（默认undo_log）
  service:
#    # 事务群组映射
    vgroupMapping:
#      # key = {tx-service-group}，需要对应
#      # value = {seataApplicationName}，Seata 服务注册名称
      goods-tx-group: seata-server
  registry:
    type: nacos
    nacos:
#      server-addr: http://127.0.0.1:8848
      server-addr: host.docker.internal:8848
      application: seata-server
  config:
    type: nacos
    nacos:
#      server-addr: http://127.0.0.1:8848
      server-addr: host.docker.internal:8848
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true # 客户端事务消息请求是否批量合并发送（默认true）
  log:
    exception-rate: 100