server:
  port: 9002
  servlet:
    context-path: /order
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/order?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123...
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*.xml
seata:
  # 与 file.conf service 中名字对应
  tx-service-group: order-tx-group
  application-id: order-seata-id
  enabled: true
  client:
    tm:
      # 一阶段全局提交结果上报TC重试次数，默认1次，建议大于1。
      commitRetryCount: 3
      # 一阶段全局回滚结果上报TC重试次数，默认1次，建议大于1
      rollbackRetryCount: 3
    undo:
      logTable: undo_log  # 自定义undo表名（默认undo_log）
  service:
    # 事务群组映射
    vgroupMapping:
      # key = {tx-service-group}，需要对应
      # value = {seataApplicationName}，Seata 服务注册名称
      order-tx-group: seata-server
    # 下面这两个属性是用于直接连接 Seata，当使用直连方式时，需要把 registry 三个属性注释掉
#    grouplist:
#      seata-server: 127.0.0.1:8091
  registry:
    # type 属性默认是：file
    type: eureka
    eureka:
      service-url: http://localhost:8761/eureka
      application: seata-server
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true # 客户端事务消息请求是否批量合并发送（默认true）
  log:
    exception-rate: 100